import './globals.css';
import { TaskProvider } from '../contexts/TaskContext'; // Ajuste o caminho conforme necessário
import { AuthProvider } from '../contexts/AuthContext'; // Ajuste o caminho conforme necessário
import RegisterServiceWorker from './register-service-worker';
import PrivateRoute from '../components/PrivateRoute'; // Ajuste o caminho conforme necessário
import localFont from "next/font/local";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: '/manifest.json'
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistSans.className}>
        <AuthProvider>
          <TaskProvider>
              {children}
          </TaskProvider>
        </AuthProvider>
        <RegisterServiceWorker />
      </body>
    </html>
  );
}

export default RootLayout;